spring:
    profiles.active: local
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

---
spring:
    profiles: local
datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product_catalog
    username: root
    password: admin
jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
---
spring:
    profiles: dev
datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product_catalog_dev
    username: root
    password: admin
jpa:
    hibernate:
        ddl-auto: update
    show-sql: true

#spring:
#    profiles.active: local
#
#---
#spring:
#    profiles: local
#datasource:
##    product-catalog:
#        #        driver-class-name: com.mysql.jdbc.Driver
#        #        driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/product_catalog
#    username: root
#    password: admin
#    jpa:
#        hibernate:
#            ddl-auto: update
##            dialect: org.hibernate.dialect.MySQLDialect
#---
#spring:
#    profiles: dev
#datasource:
#    product-catalog:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/product_catalog_dev
#        username: root
#        password: admin
#    jpa:
#        hibernate:
#            ddl-auto: update
#            dialect: org.hibernate.dialect.MySQL5Dialect